services:
  nginx:
      image: nginx:alpine-slim
      container_name: nginx
      restart: unless-stopped
      ports:
        - "80:80"
      volumes:
        - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./config/templates:/etc/nginx/templates:ro
        - /etc/letsencrypt:/etc/letsencrypt:ro
      environment:
        PORTAINER_UPSTREAM: "${PORTAINER_UPSTREAM}"
        PORTAINER_SERVER_NAME: "${PORTAINER_SERVER_NAME}"
      network_mode: bridge
