services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    volumes:
      - "${POSTGRES_DATA}:/var/lib/postgresql/data"
      - "${POSTGRES_DUMPS}:/dumps"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    network_mode: bridge
