services:
  postgres:
    image: postgres:15-trixie
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - "${BACKUP_TOOL}:/postgresql-backup"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    network_mode: bridge

volumes:
  postgres_data:
