services:
  postgres:
    image: postgres:18-trixie
    container_name: postgres
    restart: always
    volumes:
      - data:/var/lib/postgresql
      - "${BACKUP_TOOL}:/postgresql-backup"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    network_mode: bridge

volumes:
  data:
